# Generated by Django 4.2.5 on 2023-11-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidEmail_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerificationCode',
            new_name='Mail',
        ),
    ]
