# Generated by Django 4.2.5 on 2023-11-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidEmail_App', '0002_rename_verificationcode_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='verified',
        ),
    ]
